spring:
  main:
    banner-mode: "console"
  application:
    name: fiap-paquimetro-grupo01
  datasource:
    platform: h2
    url: ${DATABASE_URL:jdbc:h2:file:./db/main/fiap-paquimetro-grupo-01}
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: public
  h2:
    console:
      enabled: true
      path: /h2-console

  # MySql Database
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_tech_challenge
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'



server:
  port: 8080
  servlet:
    context-path: /fiap-paquimetro-grupo01

arsenal:
  library:
    core:
      api:
        enable-docs: true
        docs-base-package: br.com.fiap.controller